@startuml
'https://plantuml.com/component-diagram
left to right direction

node "Authentic source" #lightyellow {
    [Authorization Service]
    [Data provider]
}

node "Wallet API" #lightgreen{
  [Core Components]
    note bottom
    OpenID Connect endpoints, Trust Services, ...
    end note
  [Core Components] -l--> [KeyStorage]

  [KeyStorage]
  together {
      [LunaKeystore]
      [JKS keystore]
  }
  [KeyStorage] -l..>  [LunaKeystore] : use
  [KeyStorage] -u..> [JKS keystore] : use
  [KeyStorage] --> "Key management API"



  [Core Components] --> "Open ID Dynamic Client Registration"
  [Core Components] --> "Open ID Connect 1.0"

  [Verifier] --> OpenID4VP
  [Core Components] -- [Issuer]
  [Core Components] -- [Verifier]

  [Issuer] --> OpenID4VCI
  [Issuer] --> "SD-JWT metadata"
}



[Issuer] ..> [Authorization Service] : user auth
[Issuer] ..> [Data provider] : user data


node RP #green{
  [RelayingParty]
}
RelayingParty --> "Open ID Connect 1.0"
component EUDIW  #red
EUDIW -u--> OpenID4VCI
EUDIW -u--> "SD-JWT metadata"
EUDIW -u--> OpenID4VP

@enduml